import { data as TwDictionary } from '../tw-dict'
/**
 * LICENSE　https://github.com/g0v/moedict-data/blob/master/dict_revised/README.md
 */
export const TW_BETTER_SELECT = {
    TaiwanesePhoneticSymbols: [
        'ㄅ',
        'ㄆ',
        'ㄇ',
        'ㄈ',
        'ㄉ',
        'ㄊ',
        'ㄋ',
        'ㄌ',
        'ㄍ',
        'ㄎ',
        'ㄏ',
        'ㄐ',
        'ㄑ',
        'ㄒ',
        'ㄓ',
        'ㄔ',
        'ㄕ',
        'ㄖ',
        'ㄗ',
        'ㄘ',
        'ㄙ',
        'ㄧ',
        'ㄨ',
        'ㄩ',
        'ㄚ',
        'ㄛ',
        'ㄜ',
        'ㄝ',
        'ㄞ',
        'ㄟ',
        'ㄠ',
        'ㄡ',
        'ㄢ',
        'ㄣ',
        'ㄤ',
        'ㄥ',
        'ㄦ',
    ],
    dictionary: TwDictionary,
}
